apiVersion: haconiwa.dev/v1
kind: Space
metadata:
  name: multiroom-test
spec:
  nations:
  - id: jp
    name: Japan
    cities:
    - id: tokyo
      name: Tokyo
      villages:
      - id: test-village
        name: Test Village
        companies:
        - name: test-multiroom-company
          grid: 8x4
          basePath: ./test-multiroom-desks
          organizations:
          - id: "01"
            name: "Frontend Development Team"
            tasks: ["UI/UX Design", "React Development", "Component Testing", "State Management"]
          - id: "02" 
            name: "Backend Development Team"
            tasks: ["API Development", "Database Design", "Server Optimization", "Microservices"]
          - id: "03"
            name: "DevOps Infrastructure Team"  
            tasks: ["CI/CD Pipeline", "Container Management", "Monitoring Setup", "Cloud Infrastructure"]
          - id: "04"
            name: "Quality Assurance Team"
            tasks: ["Test Planning", "Automation Testing", "Bug Tracking", "Performance Testing"]
          gitRepo:
            url: "https://github.com/dai-motoki/haconiwa"
            defaultBranch: "main"
            auth: "https"
          buildings:
          - id: headquarters
            name: Company Headquarters
            floors:
            - level: 1
              rooms:
              - id: room-01
                name: Alpha Development Room
                description: "Main development environment for active features"
              - id: room-02
                name: Beta Testing Room
                description: "Testing and QA environment for feature validation"

---
# Task CRDs - 日時時間スタイル命名規則（YYYYMMDDHHMMSS_task-content_識別番号）
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061748_frontend-ui-design_01
spec:
  branch: 20250609061748_frontend-ui-design_01
  worktree: true
  assignee: org01-pm-r1
  spaceRef: test-multiroom-company
  description: "フロントエンドUI設計とコンポーネント実装"

---
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061749_backend-api-development_02
spec:
  branch: 20250609061749_backend-api-development_02
  worktree: true
  assignee: org02-pm-r1
  spaceRef: test-multiroom-company
  description: "REST API開発とデータベース連携"

---
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061750_database-schema-design_03
spec:
  branch: 20250609061750_database-schema-design_03
  worktree: true
  assignee: org03-wk-a-r1
  spaceRef: test-multiroom-company
  description: "データベーススキーマ設計とマイグレーション作成"

---
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061751_devops-ci-cd-pipeline_04
spec:
  branch: 20250609061751_devops-ci-cd-pipeline_04
  worktree: true
  assignee: org04-wk-a-r1
  spaceRef: test-multiroom-company
  description: "CI/CDパイプライン構築とインフラ自動化"

---
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061752_user-authentication_05
spec:
  branch: 20250609061752_user-authentication_05
  worktree: true
  assignee: org01-wk-a-r2
  spaceRef: test-multiroom-company
  description: "ユーザー認証機能の実装とセキュリティ強化"

---
apiVersion: haconiwa.dev/v1
kind: Task
metadata:
  name: 20250609061753_performance-optimization_06
spec:
  branch: 20250609061753_performance-optimization_06
  worktree: true
  assignee: org02-wk-b-r2
  spaceRef: test-multiroom-company
  description: "パフォーマンス最適化とクエリ改善" 