organization_id: org-01

boss:
  model: gemini-2.0-flash-exp
  parameters:
    temperature: 0.7
    max_tokens: 4096
    top_p: 0.95
  capabilities:
    task_decomposition: true
    progress_tracking: true
    quality_control: true
    resource_optimization: true
  learning:
    enabled: true
    model_update_interval: 24h
    performance_metrics_window: 7d

workers:
  frontend:
    model: claude-3-5-sonnet
    specialization: ui_ux
    capabilities:
      - react_development
      - vue_development
      - angular_development
      - web_accessibility
    skill_level: expert
  
  backend:
    model: gpt-4o
    specialization: server_side
    capabilities:
      - api_development
      - database_design
      - system_architecture
      - security_implementation
    skill_level: expert
    
  qa:
    model: gemini-2.0-flash-exp
    specialization: testing
    capabilities:
      - automated_testing
      - performance_testing
      - security_testing
      - regression_testing
    skill_level: expert

task_management:
  priority_levels:
    - critical
    - high
    - medium
    - low
  assignment_rules:
    - skill_match_weight: 0.4
    - workload_balance_weight: 0.3
    - urgency_weight: 0.3
  max_concurrent_tasks_per_worker: 3
  review_required: true

communication:
  protocol: grpc
  message_format: protobuf
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 1.5
  log_level: info
  metrics_enabled: true

resources:
  cpu:
    limit_per_worker: 2
    total_limit: 8
  memory:
    limit_per_worker: 2Gi
    total_limit: 8Gi
  storage:
    limit_per_worker: 10Gi
    total_limit: 50Gi
  network:
    bandwidth_limit: 100Mbps

optimization:
  auto_scaling: true
  load_balancing: true
  performance_monitoring: true
  resource_allocation_strategy: dynamic

security:
  authentication:
    method: jwt
    token_expiry: 8h
  authorization:
    role_based: true
    roles:
      - admin
      - developer
      - viewer
  encryption:
    at_rest: aes-256-gcm
    in_transit: tls-1.3
  audit:
    enabled: true
    retention_period: 90d

backup:
  schedule: "0 0 * * *"
  retention:
    count: 7
    duration: 30d
  type: incremental

monitoring:
  metrics_interval: 60s
  health_check_interval: 30s
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 85
    error_rate: 5
  notification_channels:
    - slack
    - email